//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupremeBioSolutionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MasterTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_MasterTable()
        {
            this.M_ProductMaster = new HashSet<M_ProductMaster>();
        }
    
        public int MasterId { get; set; }
        public string MasterValue { get; set; }
        public string MasterTable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ProductMaster> M_ProductMaster { get; set; }
    }
}
