//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupremeBioSolutionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ProductMaster
    {
        public int ProductId { get; set; }
        public int TypeOfProduct { get; set; }
        public string ProductName { get; set; }
        public string SubTag { get; set; }
        public string COMPOSITION { get; set; }
        public string DOSAGE { get; set; }
        public string Prd_FUNCTION { get; set; }
        public string PRESENTATION { get; set; }
        public string Prod_Pics { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_MasterTable M_MasterTable { get; set; }
    }
}
